name: lokapandu
description: "Lokapandu Flutter Project"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.1
  envied: ^1.2.1
  
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.0
  firebase_ai: ^3.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  get_it: ^8.2.0
  flutter_svg: ^2.2.1
  lottie: ^3.3.2
  cached_network_image: ^3.4.1
  iconify_design: ^1.0.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  google_fonts: ^6.3.2

  


  brick_offline_first_with_supabase: ^2.1.0
  brick_sqlite: ^4.1.0
  brick_supabase: ^2.1.0
  brick_core: ^2.0.0
  brick_offline_first: ^4.0.1
  sqflite_common: ^2.5.6
  sqflite: ^2.4.2

  #downgrade
  build_runner: ^2.5.4
  go_router: ^16.2.4
  google_maps_flutter: ^2.13.1
<<<<<<< HEAD
  shared_preferences: ^2.5.3
=======
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.0
  firebase_analytics: ^12.0.2
>>>>>>> team
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  brick_offline_first_with_supabase_build: ^2.0.0

  # downgrade
  envied_generator: ^1.1.1
  freezed: ^3.0.6
  json_serializable: ^6.9.5


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
